[package]
name = "aoc_runner"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc_runner_core = { path = "../aoc_runner_core" }
aoc_runner_macros = { path = "../aoc_runner_macros" }
itertools = "^0.12.0"
ureq = "^2.9.1"
